group-id: iap

server:
  port: 8888
  servlet:
    context-path: /xxl-job-admin

spring:
  application:
    name: xxl-job-admin #设置项目名称
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:192.168.6.68:8899} #Nacos服务接口(不能加http前缀)，直接访问localhost:8848/nacos可以进入管理页面
        namespace: ${NAME_SPACE:mesdev}
      config:
        server-addr: ${NACOS_HOST:192.168.6.68:8899}
        file-extension: yml # 配置文件的格式，默认为properties
        namespace: ${NAME_SPACE:mesdev}
        group: ${group-id}
    sentinel:
      transport:
        port: 8086
        dashboard: ${SENTINEL_HOST:192.168.6.68:8086}
      # 服务启动直接建立心跳连接
      eager: true
      datasource:
        ds:
          nacos:
            server-addr: ${NACOS_HOST:192.168.6.68:8899}
            dataId: ${spring.application.name}-sentinel
            groupId: ${group-id}
            data-type: json
            rule-type: flow
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      auto-commit: true
#      connection-test-query: SELECT 1
#      connection-timeout: 10000
#      idle-timeout: 30000
#      max-lifetime: 900000
#      maximum-pool-size: 30
#      minimum-idle: 10
#      pool-name: HikariCP
#    password: Sap2cool
#    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:mysql://119.3.29.106:3306/itl-iap?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
#    username: root
  freemarker:
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
    suffix: .ftl
    templateLoaderPath: classpath:/templates/
  mail:
    from: 1219935268@qq.com
    host: smtp.qq.com
    password: huykwukzfluphabg
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
            required: true
    username: 1219935268@qq.com # 1219935268@qq.com
  mvc:
    servlet:
      load-on-startup: 0
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/

management:
  health:
    mail:
      enabled: false
  server:
    servlet:
      context-path: /actuator
mybatis:
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml

xxl:
  job:
    accessToken: ''
    i18n: zh_CN
    logretentiondays: 30
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100
